### ISSUE TITLE
Project Name Change

### ISSUE THREAD

**Issue by progfolio** [tecosaur/lexic#1]
prior art:
- https://github.com/stardiviner/sdcv.el
- https://github.com/manateelazycat/sdcv

The first package is on MELPA.
It would be better for the project to disambiguate itself from these previous projects.

**Comment by tecosaur** [comment]
I'll be the first to admit the current name is somewhat uninspired :sweat_smile: might you have any suggestions?

**Comment by progfolio** [comment]
Nothing specific yet, but the name:

- should be short and unique.

The package name will act as a pseudo elisp namespace. Keeping it short makes the code easier to read/write/maintain.

- should communicate the purpose of the package over its implementation details.

 For now this package is tied to `sdcv`, but that could change in the future for any number of reasons. Perhaps you want to expand it to be able to use other dictionary back-ends, perhaps `sdcv` changes its name or is superseded by a fork with a different name (stardict is itself a fork of stardic). By naming the package something that communicates the purpose (an Emacs dictionary interface) you aren't bound to the implementation details.


You could give a subtle nod to stardict by using something related to astrology related, or go more general and use something related to dictionaries or language.

How about "lexic"?
https://www.wordnik.com/words/lexic
"lexic.el" sounds like "lexical"?

**Comment by tecosaur** [comment]
Thanks for the detailed response, I've found it helpful :smiley: 

Since I'd quite like to make this open to other dict formats in the future (likely via a future GoldenDict CLI), and this is used for more than just definitions - lexic sounds like it could fit quite nicely! Thanks for the suggestion.

I'll try switching to that at some point within the next week.

**Comment by progfolio** [comment]
You're welcome. Another option is "lexis":
```
 noun: lexis

    the total stock of words in a language.
    "a notable loss of English lexis"
        the level of language consisting of vocabulary, as opposed to grammar or syntax.

Origin
1950s (denoting the wording in a piece of writing): from Greek, literally ‘word’ (see lexicon).
```
Though, I do like the way "lexic.el" works.

In any case I look forward to seeing this package develop. I have my own small sdcv Emacs interface, but I'd rather contribute to this one. I'll give the code a look over and tell you what I think.

**Comment by tecosaur** [comment]
Thanks :) This was hacked together over the period of ~2 days, so there are absolutely some rough edges at the moment - I'll try to smooth them other with the name change.

I look forward to your future contributions/comments!

**Comment by progfolio** [comment]
In all honesty, after looking over the code, I think it may be best to start fresh. There are some decent ideas, but everything is tied so tightly to sdcv. I may take a crack at writing something more generic.**

**Comment by tecosaur** [comment]
For opening up more possibilities than just sdcv, I'm thinking chopping out a large chunk and re-implementing it in a more generic fashion will be what ends up happening.

Despite the current state of the code, it's still my intent to have this end up as a generic "word info" package supporting multiple backends.

Just be warned that if you make a new project I'm liable to wander over and blatantly steal your hard work 😛 (as long as you don't mind, of course).

**Comment by progfolio** [comment]
Please do. Whatever I end up with will be under GPL3. The more ideas the better. I will keep an eye on this and offer up any ideas that come to mind.

**Comment by tecosaur** [comment]
Hi @progfolio &#x2014; for your interest, I&rsquo;ve recently started looking at this, kicking off with a quick `s/sdcv/lexic/`. From here I&rsquo;m going to try to abstract the method used into a generalised backend definition.

Hopefully I&rsquo;ll be able to get this to a state where I&rsquo;m happy to push in a week or two &#x2014; unfortunately I seem to have developed a number of tasks competeing for my attention.

That&rsquo;s it for now. Hope you enjoyed the little status update :P
