### ISSUE TITLE
Webster 1913 dictionary has no color

### ISSUE THREAD

**Issue by PlasmaShift** [tecosaur/lexic#16]
Coloring needs support in your files to work correct?

It looks like you have color on Webster 1913 dictionary from the lexic.gif but the version I have has no such coloring. Is there a way to add coloring to the Webster 1913 dictionary or a better place to grab this dictionary? Can you get coloring on this dictionary?

I got the dictionary from here
https://s3.amazonaws.com/jsomers/dictionary.zip
http://jsomers.net/blog/dictionary

**Comment by tecosaur** [comment]
It would be good to know what you're seeing and how you set it up. Also look at the docstring for `lexic-format-webster` for where I downloaded it from.

**Comment by PlasmaShift** [comment]
I am have it byte complied on Emacs 28 master .manually calling the key bindings. I think I got them from the same place but I overwrote my webter1913 dictionary with these
`(require 'lexic) `
![2021-07-09-130234_1600x900_scrot](https://user-images.githubusercontent.com/2329972/125125651-20459480-e0b7-11eb-9d30-f3c4ae8dc9cc.png)

**Comment by tecosaur** [comment]
The mode is now derived from `fundamental-mode` instead of `text-mode`, I'm hoping this could fix your issue. Mind giving the latest version a shot?

**Comment by PlasmaShift** [comment]
I just tested #25c8d83 and I now get colors thanks :)
Thank you for this awesome package along with a listing of great offline dictionaries that are supported and recommended.
