### ISSUE TITLE
Some improvement proposals

### ISSUE THREAD

**Issue by minad** [tecosaur/lexic#17]
- Use fundamental-mode (Fixes #16)
- Do not use a persistent process (sdcv will pick up changes automatically, no unnecessary process buffers, ...)
- remove visual-fill-column dependency (works well without it?)
- Maybe improve the help a little bit to make it easier to setup, in particular regarding dict installation (No t at the end of dic, example file hierarchy of the dict lstree)

I've also seen some encoding issues, I will report when I see it again.

**Comment by tecosaur** [comment]
These have now all been implemented.
