### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by minad** [tecosaur/lexic#22]
sdcv Architecture with the webster 1913. I see this:

~~~
​​​Ar"chi*tec`ture ?; 135
~~~

**Comment by tecosaur** [comment]
I believe those marks are to indicate pronunciation, you can see them on https://www.websters1913.com/words/Architecture too.

**Comment by minad** [comment]
Oh, okay, that's odd. Feel free to close this then. Or you could polish this somehow.

**Comment by tecosaur** [comment]
If I could work out what modern diacritic marks are meant I think I could maybe prettify it, but I'd want to find some sort of dictionary-expert :stuck_out_tongue:

**Comment by minad** [comment]
Fair enough. It is a minor or non-issue even. It is okay to display the dictionary output unmodified.

**Comment by tecosaur** [comment]
I was able to find a reference for some, which is what went into

https://github.com/tecosaur/lexic/blob/26c7cdac16ac3042eb47438a0fb34ed4ee6fa618/lexic.el#L1400-L1484

but as you've found, that doesn't cover everything.
