### ISSUE TITLE
Adding a dictionary to `lexic-dictionary-specs` not taken into account

### ISSUE THREAD

**Issue by brabalan** [tecosaur/lexic#3]
I added this to my configuration
``` emacs-lisp
(after! lexic
  (push '("​​dictd_www.dict.org_gcide"
          :short "GCIDE"
          :formatter lexic-format-webster
          :priority 1)
        lexic-dictionary-specs))
```

but I still see `​​dictd_www.dict.org_gcide` entries under that name and not formatted. Am I doing it wrong?

**Comment by tecosaur** [comment]
At a glance, that looks like it should work. The part used for matching the dictionary is [this line](https://github.com/tecosaur/lexic/blob/0cab59dbe40d33b7ffed0478ce1aae8d760281c3/lexic.el#L512). If you redefine `lexic-parse-results` to add a line like
```elisp
(with-current-buffer (get-buffer-create "*lexic-raw*")
  (insert result))
```
you can navigate to that buffer and check the regex etc. works as expected. Call `lexic-parse-results` with the buffer content and you'll see what the recognised `dict` is.

If you can check these details, it will be much easier to see what's going on :)

**Comment by brabalan** [comment]
There must have been some weird control characters in my string… I copied the one lexic expects (by edebugging `lexic-dictionary-spec`) and although it looks the same, everything now works. Sorry for the noise.
