### ISSUE TITLE
 ERROR: timeout waiting for lexic

### ISSUE THREAD

**Issue by bnicenboim** [tecosaur/lexic#9]
I'm using this config in doom, while `define-word-at-point` gives me some results, `lexic-search-word-at-point` is saying:
` ERROR: timeout waiting for lexic`

```
(use-package! lexic
  :commands lexic-search lexic-list-dictionary
  :config
  (map! :map lexic-mode-map
        :n "q" #'lexic-return-from-lexic
        :nv "RET" #'lexic-search-word-at-point
        :n "a" #'outline-show-all
        :n "h" (cmd! (outline-hide-sublevels 3))
        :n "o" #'lexic-toggle-entry
        :n "n" #'lexic-next-entry
        :n "N" (cmd! (lexic-next-entry t))
        :n "p" #'lexic-previous-entry
        :n "P" (cmd! (lexic-previous-entry t))
        :n "C-p" #'lexic-search-history-backwards
        :n "C-n" #'lexic-search-history-forwards
        :n "/" (cmd! (call-interactively #'lexic-search))))


(defadvice! +lookup/dictionary-definition-lexic (identifier &optional arg)
  "Look up the definition of the word at point (or selection) using `lexic-search'."
  :override #'+lookup/dictionary-definition
  (interactive
   (list (or (doom-thing-at-point-or-region 'word)
             (read-string "Look up in dictionary: "))
         current-prefix-arg))
  (lexic-search identifier nil nil t))
```
Am I missing something obvious?

**Comment by tecosaur** [comment]
Interesting. That looks like my config and it works for me... Does sdcv work on the command line?

**Comment by bnicenboim** [comment]
ha, no. I never installed it. Ok, I'll install it and try again

**Comment by tecosaur** [comment]
I could probably add an "if timeout, was sdcv around?" check.
I want to abstract out the definition sources first, so that sdcv isn't hardcoded in as *the* backend (just haven't had the time yet).

BTW, you'll also want to grab sme dicts.

**Comment by bnicenboim** [comment]
Ok, I followed the instructions [here](https://askubuntu.com/questions/191125/is-there-an-offline-command-line-dictionary/191268#191268). And sdcv works from the command line, but I get

`helm-M-x-execute-command: Wrong type argument: char-or-string-p, nil`

**Comment by tecosaur** [comment]
Interesting. I haven't seen that before, not sure what's going on. A trace would be useful.

**Comment by bnicenboim** [comment]
I should mention that I'm quite new to emacs :) 
How do I get a trace?

**Comment by tecosaur** [comment]
Try `M-x set-variable RET debug-on-error RET t RET` then triggering the issue. Copy the popup buffer contents and share them here :)

**Comment by bnicenboim** [comment]
I just restarted doom and it works :)
Thanks!
